stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\NYC_Taxi_Trip_Duration.csv
    deps:
    - .\data\raw\NYC_Taxi_Trip_Duration.csv
    - .\src\data\make_dataset.py
    params:
    - make_dataset.test_split
    - make_dataset.seed
  build_features:
    cmd: python .\src\features\build_features.py .\data\interim\train.csv  .\data\interim\test.csv
    deps: 
    - .\data\interim\train.csv
    - .\data\interim\test.csv
    - .\src\features\build_features.py

    